// Generated by https://quicktype.io

export interface DashboardResponse {
    numberOfOrders:       number;
    paidOrders:           number;
    unpaidOrders:         number;
    numberOfUsers:        number;
    numberOfProducts:     number;
    productsWithNoStock:  number;
    productsWithLowStock: number;
}
